version: '3'
services:
  redis:
    image: redis:5.0.0
    restart: "no"
    container_name: redis
    ports:
      - "6010:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true