version: '3'
services:
  redis:
    image: redis:6.2.6
    restart: always
    container_name: redis
    ports:
      - '16379:16379'
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - /home/vjudge/_cache/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true