version: '3.6'

services:
  mysql:
    restart: always
    image: mysql:5.7.31
    container_name: mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 6020:3306
    expose:
      # Opens port 3306 on the container
      - 3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_USER: test
      MYSQL_PASS: qwe@168
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
    volumes:
      - /tmp/_docker/mysql/data:/var/lib/mysql
      - /tmp/_docker/mysql/config:/etc/mysql/conf.d

